# default

spring:
  application:
    name: molly-h5

  datasource:
    url: jdbc:mysql://39.106.129.224:3306/molly_h5_dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: syrup
    password: 'C&UcXT!sTs^gip^k'

    initialization-mode: always

server:
  address: 127.0.0.1
  port: 5305

logging:
  level:
    org.springframework.jdbc.core: INFO
