# prod

spring:
  application:
    name: molly-h5

  datasource:
    url: jdbc:mysql://rm-2ze51mfu65cq5wbv1.mysql.rds.aliyuncs.com:3306/molly_h5?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: syrup
    password: 'wx8Ko$klS1ufMYBQ'

    initialization-mode: always

server:
  address: 127.0.0.1
  port: 5305

logging:
  file: /kt/log/molly-h5/molly-h5-server.log
  level:
    org.springframework.jdbc.core: INFO
